### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by JABIoT** [AnthonyKNorman/Xiaomi_LYWSD03MMC_for_HA#7]
It was working well for a few days other than having to restart the ESP once per day but now it is no longer working.
I have replaced ble.py and mqtt.py with the files last updated (4 days ago at the time of this post) and applied the changes to mqtt.py to support user/password on broker but still unable to get it going.
I am not wizard enough to understand what might be the issue by looking at the code on the specified line numbers.
Any help would be appreciated.

This is what I get when connecting and resetting the ESP:
`
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:4988
load:0x40078000,len:11408
load:0x40080400,len:6108
entry 0x400806bc
I (592) psram: This chip is ESP32-D0WD
E (592) spiram: SPI RAM enabled but initialization failed. Bailing out.
I (592) cpu_start: Failed to init external RAM; continuing without it.
I (599) cpu_start: Pro cpu up.
I (603) cpu_start: Application information:
I (608) cpu_start: Compile time:     Dec 20 2019 07:58:58
I (614) cpu_start: ELF file SHA256:  0000000000000000...
I (620) cpu_start: ESP-IDF:          v4.0-beta1
I (625) cpu_start: Starting app cpu, entry point is 0x400835e0
I (0) cpu_start: App cpu up.
I (636) heap_init: Initializing. RAM available for dynamic allocation:
I (642) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (648) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM
I (655) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM
I (661) heap_init: At 3FFBDB5C len 00000004 (0 KiB): DRAM
I (667) heap_init: At 3FFCCA50 len 000135B0 (77 KiB): DRAM
I (673) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (679) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (686) heap_init: At 4009E2E4 len 00001D1C (7 KiB): IRAM
I (692) cpu_start: Pro cpu start user code
I (710) spi_flash: detected chip: generic
I (711) spi_flash: flash io: dio
I (711) cpu_start: Chip Revision: 1
W (712) cpu_start: Chip revision is higher than the one configured in menuconfig                                                                                      . Suggest to upgrade it.
I (723) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
E (40) spiram: SPI RAM not initialized
I (190) modsocket: Initializing
I (1893) phy: phy_version: 4102, 2fa7a43, Jul 15 2019, 13:06:06, 0, 0
Connection successful
('172.16.0.52', '255.255.255.0', '172.16.0.1', '172.16.2.15')
2020-07-26 21:52:26
Connected to 172.16.0.126 MQTT broker
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "mqtt.py", line 58, in <module>
  File "ble.py", line 55, in __init__
  File "ble.py", line 47, in debug
NameError: name 'Exceptions' isn't defined
MicroPython v1.12 on 2019-12-20; ESP32 module (spiram) with ESP32
Type "help()" for more information.
>>> import mqtt.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'mqtt.py'
>>> python ver
Traceback (most recent call last):
  File "<stdin>", line 1
SyntaxError: invalid syntax
>>> ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:4988
load:0x40078000,len:11408
load:0x40080400,len:6108
entry 0x400806bc
I (592) psram: This chip is ESP32-D0WD
E (592) spiram: SPI RAM enabled but initialization failed. Bailing out.
I (592) cpu_start: Failed to init external RAM; continuing without it.
I (599) cpu_start: Pro cpu up.
I (603) cpu_start: Application information:
I (608) cpu_start: Compile time:     Dec 20 2019 07:58:58
I (614) cpu_start: ELF file SHA256:  0000000000000000...
I (620) cpu_start: ESP-IDF:          v4.0-beta1
I (625) cpu_start: Starting app cpu, entry point is 0x400835e0
I (0) cpu_start: App cpu up.
I (636) heap_init: Initializing. RAM available for dynamic allocation:
I (642) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (648) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM
I (655) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM
I (661) heap_init: At 3FFBDB5C len 00000004 (0 KiB): DRAM
I (667) heap_init: At 3FFCCA50 len 000135B0 (77 KiB): DRAM
I (673) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (679) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (686) heap_init: At 4009E2E4 len 00001D1C (7 KiB): IRAM
I (692) cpu_start: Pro cpu start user code
I (710) spi_flash: detected chip: generic
I (711) spi_flash: flash io: dio
I (711) cpu_start: Chip Revision: 1
W (713) cpu_start: Chip revision is higher than the one configured in menuconfig. Suggest to upgrade it.
I (723) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
E (40) spiram: SPI RAM not initialized
I (190) modsocket: Initializing
I (1883) phy: phy_version: 4102, 2fa7a43, Jul 15 2019, 13:06:06, 0, 0
Connection successful
('172.16.0.52', '255.255.255.0', '172.16.0.1', '172.16.2.15')
2020-07-26 21:56:31
Connected to 172.16.0.126 MQTT broker
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "mqtt.py", line 58, in <module>
  File "ble.py", line 55, in __init__
  File "ble.py", line 47, in debug
NameError: name 'Exceptions' isn't defined
MicroPython v1.12 on 2019-12-20; ESP32 module (spiram) with ESP32
Type "help()" for more information.
>>>
`

**Comment by AnthonyKNorman** [comment]
Sorry, my fault. 'Exceptions' is not valid. I should be 'Exception' on line 47 in ble.py.
I will fix, test and upload.

**Comment by AnthonyKNorman** [comment]
New version of ble.py uploaded
